# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171213_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credit_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
